name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-22.05

      - name: Check code
        run: nix-shell --command "just check"

      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: check code, `GithubCI`
          branch: ${{ github.head_ref }}

  build:
    runs-on: ubuntu-latest
    needs: [lint-and-format]
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-22.05

      # TODO add crossbuild testing
      - name: Build
        run: nix-shell --command "just build"

      - name: Test
        run: go test -v ./...
